trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SELENIUM_GRID_IP: '20.244.105.116'
  SELENIUM_GRID_PORT: '4444'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test -Dselenium.grid.ip=$(SELENIUM_GRID_IP) -Dselenium.grid.port=$(SELENIUM_GRID_PORT)'

- script: |
    mkdir -p $(System.DefaultWorkingDirectory)/ExtentReports
    cp -r $(System.DefaultWorkingDirectory)/reports $(System.DefaultWorkingDirectory)/ExtentReports/reports
  displayName: 'Copy Reports to ExtentReports'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/ExtentReports'
    ArtifactName: 'ExtentReports'
    publishLocation: 'Container'