trigger:
- main

pool:
  name: 'Default'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Uninstall Docker
      docker rm -f $(docker ps -aq)
      docker rmi -f $(docker images -aq)
      sudo systemctl stop docker.socket
      sudo apt-get purge -y docker* containerd* runc
      sudo rm -rf /var/lib/docker
      sudo rm -rf /var/lib/containerd
      sudo rm -rf /etc/docker
      sudo rm -rf /etc/systemd/system/docker.service
      sudo rm -rf /etc/systemd/system/docker.socket
      sudo rm -rf /usr/libexec/docker
      sudo rm -rf /usr/bin/docker
      sudo rm -rf /usr/local/bin/docker-compose
      sudo groupdel docker

      # Install Docker and start Selenium Grid
      sudo apt update
      sudo apt install -y docker.io
      sudo chmod 777 /var/run/docker.sock
      docker pull selenium/standalone-chrome
      docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" -e SE_NODE_SESSION_TIMEOUT=45 -e SE_NODE_MAX_SESSIONS=2 -e SE_NODE_OVERRIDE_MAX_SESSIONS=true selenium/standalone-chrome:latest